### ISSUE TITLE
Role restriction issue

### ISSUE THREAD

**Issue by Qweryology** [calico-crusade/botsdotnet#1]
it seems that role restriction for botsdotnet.palringo does not work,
I tried to replicate the built in role selection code and could not get that to work, however, by doing

```
            var hold = msg.Group.Original.Original as BotsDotNet.Palringo.SubProfile.Group;
            var ahh = hold.Members.Where(t => t.Key == user.Id).FirstOrDefault().Value;
            return ahh;
```
i was able to return the role, the code in rolerestrictions does not have the .original.original

**Comment by calico-crusade** [comment]
What is the purpose of this? If you're looking for role-based restrictions (such as Admin, Mod, ect), those are built in. The implementation of these role based restrictions live [here](https://github.com/calico-crusade/botsdotnet/blob/master/BotsDotNet.Palringo/Restrictions/RoledRestriction.cs).

Those can also be used as an example of how to use restrictions in general.

**Comment by calico-crusade** [comment]
I did find an issue with this. I have fixed it and released a new version of the library on nuget. see version 1.1.0
